name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v6
            -   name: Archive Release
                uses: thedoctor0/zip-release@0.7.5
                with:
                    type: zip
                    directory: custom_components/ebusd_vaillant
                    filename: ebusd_vaillant.zip
            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                    draft: false
                    generate_release_notes: false
                    files: custom_components/ebusd_vaillant/ebusd_vaillant.zip
